# -*- coding: utf-8 -*-
"""KodePrima.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12lGto2zFTZXfG3lifNKl3Ts2fDmSNlfA
"""

# Menentukan bilangan prima

n = int(input('Masukkan bilangan: '))

prima = True # Inisialisasi bahwa bilangan yang diinput adalah prima

if n < 2: # Kasus khusus
  prima = False
else:
  for i in range(2,n): # Loop berjalan dari i = 2 sampai i = n - 1
    if (n % i == 0): # Menentukan apakah n habis dibagi i
      prima = False # Jika ditemukan n habis dibagi i maka prima berubah menjadi false

if prima:
  print('Bilangan prima')
else:
  print('Bukan bilangan prima')